name: Doxygen Documentation Generation

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v2

      - name: Run Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: ./Doxygen
          enable-latex: true

      - name: Deploy Documentation to Gh-Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc_output
